<table>
<tr>
    <td>
        <a href="<?php echo $this->baseUrl('/blogshanty/index/');?>">Go to Homepage</a>
        <a href="<?php echo $this->baseUrl('/blogshanty/index/login/');?>">Login</a>
    </td>     
</tr>    
<form name="signupfrm" id="signupfrm" method="post" action="">    
<tr>   
    <td>   
       <?php echo $this->signUpForm->username;?>
    </td> 
</tr>
<tr>    
    <td>
       <?php echo $this->signUpForm->email;?> 
    </td> 
</tr>
<tr>    
    <td>
       <?php echo $this->signUpForm->pass;?>
    </td> 
</tr> 
<tr>    
    <td align="center">
       <?php echo $this->signUpForm->submit;?>
    </td> 
</tr>
</form>
</table>