<table>
<tr>
    <td>
        <a href="<?php echo $this->baseUrl('/blogbas/index/');?>">Go to Homepage</a>         
    </td>     
</tr>    
<form name="blogpostfrm" id="blogpostfrm" method="post" action="">
<tr>    
    <td>      
       <?php echo $this->blogPostForm->title;?>
    </td> 
</tr>
<tr>    
    <td>       
       <?php echo $this->blogPostForm->body;?> 
    </td> 
</tr> 
<tr>    
    <td>
       <?php echo $this->blogPostForm->tags;?>  
    </td> 
</tr>  
<tr>    
    <td align="center">
       <?php echo $this->blogPostForm->submit;?>     
    </td> 
</tr>
</form>
</table>