<table>
<?php
if($this->username) {
?>
<tr> 
    <td>
        <a href="<?php echo $this->baseUrl('/blogbas/index/blogpost');?>">Post a blog</a>   
    </td>
    <td>
        <a href="<?php echo $this->baseUrl('/blogbas/index/logout');?>">Logout</a>   
    </td> 
</tr>  
<?php
} else {
?>
<tr> 
    <td colspan="2">
        <a href="<?php echo $this->baseUrl('/blogbas/index/login');?>">Login</a>   
    </td>    
</tr>  
<?php
}
?>
<tr>   
    <td>
        <label>Username</label>   
    </td> 
    <td>
        <label>Title</label>   
    </td>
    <td>
        <label>Body</label>   
    </td>
</tr>
<?php
if($this->allusers) {
foreach($this->allusers as $user) {
       
       $blogid = $user->__get('_id');
       $title = $user->__get('title');
       $body  = $user->__get('body');
       $username = $user->__get('user');
?>
<tr>   
    <td>
        <a href="<?php echo $this->baseUrl('/blogbas/index/addcomment/blogid/'.$blogid);?>"><?php echo $username;?></a>
    </td>
    <td><?php echo $title;?></td> 
    <td><?php echo $body;?></td>    
</tr> 
<?php
}
} else {
?>
<tr>
    <td colspan="3">No Record Found.</td>
</tr>
<?php
}
?>
</table>
