<table>
<form name="blogpostfrm" id="blogpostfrm" method="post" action="">
<tr>
    <td>
        <label>Title :</label>    
    </td>
    <td>
       <input type="text" id="title" name="title">    
    </td> 
</tr>
<tr>
     <td>
        <label>Body :</label>    
    </td>
    <td>
       <input type="text" id="body" name="body">    
    </td> 
</tr> 
<tr>
     <td>
        <label>Tags :</label>    
    </td>
    <td>
       <input type="text" id="tags" name="tags">    
    </td> 
</tr>  
<tr>    
    <td colspan="2" align="center">
       <input type="submit" id="submit" name="submit" value="Submit">    
    </td> 
</tr>
</form>
</table>