<table>
<form name="blogpostfrm" id="blogpostfrm" method="post" action="">
<tr>
    <td>
       <?php echo $this->blogPostForm->title;?>
    </td>
</tr>
<tr>
    <td>
       <!--<input type="text" id="body" name="body">--> 
       <!--<textarea id="body" name="body"></textarea>-->
       <?php echo $this->blogPostForm->body;?> 
    </td> 
</tr> 
<tr>
    <td>
       <?php echo $this->blogPostForm->tags;?>  
    </td>
</tr>  
<tr>    
    <td align="center">
       <input type="submit" id="submit" name="submit" value="Submit">    
    </td> 
</tr>
</form>
</table>
