<table>
<form name="loginfrm" id="loginfrm" method="post" action="">
<tr>
    <td>
        <label>Username :</label>    
    </td>
    <td>
       <input type="text" id="username" name="username">    
    </td> 
</tr>
<tr>
     <td>
        <label>Password :</label>    
    </td>
    <td>
       <input type="password" id="pass" name="pass">    
    </td> 
</tr>  
<tr>    
    <td colspan="2" align="center">
       <input type="submit" id="submit" name="submit" value="Submit">    
    </td> 
</tr>
</form>
</table>